# Generated by Django 4.2.6 on 2024-01-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitayGorod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='author', to='ChitayGorod.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(related_name='lang', to='ChitayGorod.language'),
        ),
    ]
