# Generated by Django 4.2.6 on 2024-01-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChitayGorod', '0002_remove_book_author_remove_book_language_book_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desctiption',
            new_name='description',
        ),
    ]
