# Generated by Django 4.2.6 on 2024-01-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChitayGorod', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
