# Generated by Django 4.2.6 on 2024-01-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitayGorod', '0008_alter_profile_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='static/profile_pics'),
        ),
    ]
